config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "homes#top"
  get "/downloader" => "downloads#index"
  get "/ranking" => "rankings#index"
  get "/realtime" => "realtimes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/download.rb
class Download < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/ranking.rb
class Ranking < ApplicationRecord
end

app/models/realtime.rb
class Realtime < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  def index

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
end

app/controllers/realtimes_controller.rb
class RealtimesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/realtimes_helper.rb
module RealtimesHelper
end

app/views/downloads/index.html.erb
<h1>ダウンローダー</h1>
<form action="/downloader" method="post">
  <input type="text" id="">
</form>

<video controls>
  <source src="video/test.mp4">
</video>

app/views/homes/top.html.erb
<h1>トップページ</h1>

<form action="/downloader" method="post" >
  <input type="text">
  <input type="submit" value="送信する">
</form>

<form action="/twitter-video-downloader" class="row my-3" id="tweet-video-downloader">
  <div class="form-group col-8">
    <input class="form-control" id="tweet-video-downloader-target" name="target" placeholder="input tweet URL or status ID" type="text">
  </div>
</form>

<div class="video-outer"><video controls="controls"><source src="https://twitter.com/IyashiMov/status/1538793449767505923?s=20&t=SYJ_avLjKith9p_Tv9LFVQS"></video></div>

<%= link_to "リンク", downloader_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HobbyWarehouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>